/*
 * The statements below are used to prepopulate the mst3k database with data
*/

/*
 * Prepopulating the table actor with Mystery Science Theater 3000 actors
*/

INSERT INTO actor (fname, lname, wikia, imdb)
VALUES ("Joel", "Hodgson", "http://mst3k.wikia.com/wiki/Joel_Hodgson", "http://www.imdb.com/name/nm0388273/?ref_=fn_al_nm_1"),
       ("Kevin", "Murphy", "http://mst3k.wikia.com/wiki/Kevin_Murphy", "http://www.imdb.com/name/nm0614436/?ref_=nv_sr_1"),
       ("Trace", "Beaulieu", "http://mst3k.wikia.com/wiki/Trace_Beaulieu", "http://www.imdb.com/name/nm0064546/?ref_=nv_sr_1"),
       ("Jim", "Mallon", "http://mst3k.wikia.com/wiki/Jim_Mallon", "http://www.imdb.com/name/nm0540075/?ref_=fn_al_nm_1"),
       ("Frank", "Conniff", "http://mst3k.wikia.com/wiki/Frank_Conniff", "http://www.imdb.com/name/nm0175239/?ref_=fn_al_nm_1"),
       ("Josh", "Weinstein", "http://mst3k.wikia.com/wiki/Josh_Weinstein", "http://www.imdb.com/name/nm0918441/?ref_=nv_sr_1"),
       ("Michael J.", "Nelson", "http://mst3k.wikia.com/wiki/Michael_J._Nelson", "http://www.imdb.com/name/nm0625621/?ref_=nv_sr_1"),
       ("Mary Jo", "Pehl", "http://mst3k.wikia.com/wiki/Mary_Jo_Pehl", "http://www.imdb.com/name/nm0670447/?ref_=fn_al_nm_1"),
       ("Bill", "Corbett", "http://mst3k.wikia.com/wiki/Bill_Corbett", "http://www.imdb.com/name/nm0179132/"),
       ("Patrick", "Brantseg", "http://mst3k.wikia.com/wiki/Patrick_Brantseg", "http://www.imdb.com/name/nm0105304/?ref_=fn_al_nm_1");

/*
 * Prepopulating the table mst3k_character with Mystery Science Theater 3000 characters.
*/

INSERT INTO mst3k_character (fname, lname, type)
VALUES ("Joel", "Robinson", "Human"),
       ("Tom", "Servo", "Robot"),
       ("Crow T.", "Robot", "Robot"),
       ("Gypsy", NULL, "Robot"),
       ("TV's Frank", NULL, "Human"),
       ("Dr. Clayton", "Forrester", "Human"),
       ("Dr. Laurence", "Erhardt", "Human"),
       ("Mike", "Nelson", "Human"),
       ("Pearl", "Forrester", "Human"),
       ("Bobo", NULL, "Gorilla"),
       ("Brain Guy", NULL, "Alien");

/*
 * Prepopulating the table genre with genres and subgenres of the movies screened
 * in Mystery Science Theater 3000.
*/

INSERT INTO genre (genre_name, subgenre_name)
VALUES ("Adventure", "Sci-Fi"),
       ("Crime", "Music"),
       ("Western", "Action"),
       ("Sci-Fi", "Action"),
       ("Horror", "Supernatural"),
       ("Horror", "Sci-Fi"),
       ("Drama", "Music"),
       ("Sci-Fi", "Fantasy"),
       ("Action", "Fantasy"),
       ("Action", "Crime");

/*
 * Prepopulating the table movie with the movies screened in Mystery Science Theater 3000.
*/

INSERT INTO movie (title, director_fname, director_lname, year, synopsis, genre_id)
VALUES ("Teenage Caveman", "Roger", "Corman", 1958, "A rebellious teenage caveboy questions the clan’s rules and yearns to explore the land beyond the river.", (SELECT id FROM genre WHERE genre_name = "Adventure" AND subgenre_name = "Sci-Fi")),
       ("Daddy-O", "Lou", "Place", 1958, "High-panted, cool-singing, truck-driving hepcat tangles with blonde bombshell, tries to solve his friend’s murder and becomes a courier for drug dealers.", (SELECT id FROM genre WHERE genre_name = "Crime" AND subgenre_name = "Music")),
       ("Gunslinger", "Roger", "Corman", 1957, "The widow of a murdered sheriff attempts to clean up the crime in her small town with help from the man hired to kill her.", (SELECT id FROM genre WHERE genre_name = "Western" AND subgenre_name = "Action")),
       ("Warrior of the Lost World", "David", "Worth", 1984, "A nameless hero and his talking motorcycle fight an evil dictator in a post-apocalyptic world.", (SELECT id FROM genre WHERE genre_name = "Sci-Fi" AND subgenre_name = "Action")),
       ("Manos: The Hands of Fate", "Harold P.", "Warren", 1966, "A hapless family on a car trip in rural Texas takes refuge at a 'lodge' that turns out to be the home of a deadly cult.", (SELECT id FROM genre WHERE genre_name = "Horror" AND subgenre_name = "Supernatural")),
       ("The Crawling Eye", "Quentin", "Lawrence", 1958, "After some mysterious deaths in the Swiss Alps, a U.N. troubleshooter is sent to assist a scientist who is investigating the situation. But a pretty young psychic may be the most help.", (SELECT id FROM genre WHERE genre_name = "Horror" AND subgenre_name = "Sci-Fi")),
       ("Girls Town", "Charles F.", "Haas", 1959, "A teen bombshell is sent to a Catholic reform school after she’s framed for a murder.", (SELECT id FROM genre WHERE genre_name = "Drama" AND subgenre_name = "Music")),
       ("Laserblast", "Michael", "Rae", 1978, "A troubled teen finds an alien’s weapon and takes revenge on those who taunted him.", (SELECT id FROM genre WHERE genre_name = "Horror" AND subgenre_name = "Sci-Fi")),
       ("Time Chasers", "David", "Giancola", 1994, "A small-town inventor builds a time machine, only to see it misused by a greedy corporation.", (SELECT id FROM genre WHERE genre_name = "Sci-Fi" AND subgenre_name = "Fantasy")),
       ("Puma Man", "Alberto", "De Martino", 1980, "After discovering that he has inherited super powers, a mild-mannered young professor must do battle with a villain using a mind-control device.", (SELECT id FROM genre WHERE genre_name = "Action" AND subgenre_name = "Fantasy")),
       ("Final Justice", "Greydon", "Clark", 1985, "A Texas sheriff winds up on the island of Malta in pursuit of the criminal that killed his partner.", (SELECT id FROM genre WHERE genre_name = "Action" AND subgenre_name = "Crime"));

/*
 * Prepopulating the table episode with episodes of Mystery Science Theater 3000.
*/

INSERT INTO episode (title, episode_number, season_number, release_date, movie_id)
VALUES ("Teenage Caveman", 315, 3, '1991-11-09', (SELECT id FROM movie WHERE title = "Teenage Caveman")),
       ("Daddy-O", 307, 3, '1991-07-20', (SELECT id FROM movie WHERE title = "Daddy-O")),
       ("Gunslinger", 511, 5, '1993-10-09', (SELECT id FROM movie WHERE title = "Gunslinger")),
       ("Warrior of the Lost World", 501, 5, '1993-07-24', (SELECT id FROM movie WHERE title = "Warrior of the Lost World")),
       ("Manos: The Hands of Fate", 424, 4, '1993-01-30', (SELECT id FROM movie WHERE title = "Manos: The Hands of Fate")),
       ("The Crawling Eye", 101, 1, '1989-11-11', (SELECT id FROM movie WHERE title = "The Crawling Eye")),
       ("Girls Town", 601, 6, '1994-07-16', (SELECT id FROM movie WHERE title = "Girls Town")),
       ("Laserblast", 706, 7, '1996-05-18', (SELECT id FROM movie WHERE title = "Laserblast")),
       ("Time Chasers", 821, 8, '1997-11-22', (SELECT id FROM movie WHERE title = "Time Chasers")),
       ("Puma Man", 903, 9, '1998-04-04', (SELECT id FROM movie WHERE title = "Puma Man")),
       ("Final Justice", 1008, 10, '1999-06-20', (SELECT id FROM movie WHERE title = "Final Justice"));

/*
 * Prepopulating the actor_episode table to relate actors to Mystery Science Theater 3000
 * episodes that they have appeared in.
*/

INSERT INTO actor_episode (actor_id, episode_id)
VALUES ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM actor WHERE fname = "Josh" AND lname = "Weinstein"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM actor WHERE fname = "Michael J." AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM actor WHERE fname = "Michael J." AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM actor WHERE fname = "Michael J." AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM actor WHERE fname = "Michael J." AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM actor WHERE fname = "Michael J." AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM actor WHERE fname = "Mary Jo" AND lname = "Pehl"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM actor WHERE fname = "Mary Jo" AND lname = "Pehl"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM actor WHERE fname = "Mary Jo" AND lname = "Pehl"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM actor WHERE fname = "Mary Jo" AND lname = "Pehl"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM actor WHERE fname = "Bill" AND lname = "Corbett"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM actor WHERE fname = "Bill" AND lname = "Corbett"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM actor WHERE fname = "Bill" AND lname = "Corbett"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM actor WHERE fname = "Patrick" AND lname = "Brantseg"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM actor WHERE fname = "Patrick" AND lname = "Brantseg"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM actor WHERE fname = "Patrick" AND lname = "Brantseg"),
              (SELECT id FROM episode WHERE title = "Final Justice"));

/*
 * Prepopulating the actor_character table to relate actors to the Mystery Science Theater 3000
 * characters they have portrayed.
*/

INSERT INTO actor_character (actor_id, character_id)
VALUES ((SELECT id FROM actor WHERE fname = "Joel" AND lname = "Hodgson"),
              (SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo")),
       ((SELECT id FROM actor WHERE fname = "Kevin" AND lname = "Murphy"),
              (SELECT id FROM mst3k_character WHERE fname = "Bobo")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester")),
       ((SELECT id FROM actor WHERE fname = "Trace" AND lname = "Beaulieu"),
              (SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot")),
       ((SELECT id FROM actor WHERE fname = "Jim" AND lname = "Mallon"),
              (SELECT id FROM mst3k_character WHERE fname = "Gypsy")),
       ((SELECT id FROM actor WHERE fname = "Frank" AND lname = "Conniff"),
              (SELECT id FROM mst3k_character WHERE fname = "TV's Frank")),
       ((SELECT id FROM actor WHERE fname = "Josh" AND lname = "Weinstein"),
              (SELECT id FROM mst3k_character WHERE fname = "Dr. Laurence" AND lname = "Erhardt")),
       ((SELECT id FROM actor WHERE fname = "Josh" AND lname = "Weinstein"),
              (SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo")),
       ((SELECT id FROM actor WHERE fname = "Michael J." AND lname = "Nelson"),
              (SELECT id FROM mst3k_character WHERE fname = "Mike" AND lname = "Nelson")),
       ((SELECT id FROM actor WHERE fname = "Mary Jo" AND lname = "Pehl"),
              (SELECT id FROM mst3k_character WHERE fname = "Pearl" AND lname = "Forrester")),
       ((SELECT id FROM actor WHERE fname = "Bill" AND lname = "Corbett"),
              (SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot")),
       ((SELECT id FROM actor WHERE fname = "Bill" AND lname = "Corbett"),
              (SELECT id FROM mst3k_character WHERE fname = "Brain Guy")),
       ((SELECT id FROM actor WHERE fname = "Patrick" AND lname = "Brantseg"),
              (SELECT id FROM mst3k_character WHERE fname = "Gypsy"));

/*
 * Prepopulating the character_episode table to relate Mystery Science Theater 3000
 * characters to episodes they have appeared in.
*/

INSERT INTO character_episode (character_id, episode_id)
VALUES ((SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM mst3k_character WHERE fname = "TV's Frank"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Teenage Caveman")),
       ((SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM mst3k_character WHERE fname = "TV's Frank"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Daddy-O")),
       ((SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM mst3k_character WHERE fname = "TV's Frank"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Gunslinger")),
       ((SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM mst3k_character WHERE fname = "TV's Frank"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Warrior of the Lost World")),
       ((SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM mst3k_character WHERE fname = "TV's Frank"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Manos: The Hands of Fate")),
       ((SELECT id FROM mst3k_character WHERE fname = "Joel" AND lname = "Robinson"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Laurence" AND lname = "Erhardt"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "The Crawling Eye")),
       ((SELECT id FROM mst3k_character WHERE fname = "Mike" AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM mst3k_character WHERE fname = "TV's Frank"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Girls Town")),
       ((SELECT id FROM mst3k_character WHERE fname = "Mike" AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM mst3k_character WHERE fname = "Pearl" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM mst3k_character WHERE fname = "Dr. Clayton" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Laserblast")),
       ((SELECT id FROM mst3k_character WHERE fname = "Mike" AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Pearl" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Bobo"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Brain Guy"),
              (SELECT id FROM episode WHERE title = "Time Chasers")),
       ((SELECT id FROM mst3k_character WHERE fname = "Mike" AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Pearl" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Bobo"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Brain Guy"),
              (SELECT id FROM episode WHERE title = "Puma Man")),
       ((SELECT id FROM mst3k_character WHERE fname = "Mike" AND lname = "Nelson"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM mst3k_character WHERE fname = "Tom" AND lname = "Servo"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM mst3k_character WHERE fname = "Crow T." AND lname = "Robot"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM mst3k_character WHERE fname = "Gypsy"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM mst3k_character WHERE fname = "Pearl" AND lname = "Forrester"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM mst3k_character WHERE fname = "Bobo"),
              (SELECT id FROM episode WHERE title = "Final Justice")),
       ((SELECT id FROM mst3k_character WHERE fname = "Brain Guy"),
              (SELECT id FROM episode WHERE title = "Final Justice"));
